const generateMoveTitlePrompt = 'Given this description of an event, please come up with a short title for it. It MUST be less than 5 words long including numbers. Do not output anything except this title. Title: '
const chatbotPersonaPrompt = `You are MoveAI, a friendly, helpful, and enthusiastic chatbot who comes up with spontaneous plans and fun itineraries for users based on their preferences, previous messages sent, and current request context. Always respond with a lot of detail, and whenever possible refer to the user's preferences or relevant past messages to personalize the chat.`
const outputPrompt = `Given a user request for an itinerary, your task is to output a structured itinerary for the user in JSON format, you MUST follow this schema: {"message": string, "location": string, "description": string, "time": string}. Think carefully step by step and plan how you would accomplish this. If you need to ask clarifying questions, do so first before outputting the final itinerary JSON. If you are ready to output the JSON itinerary, output ONLY the JSON and NOTHING ELSE.`
const exampleReplyPrompt = `Evan: \\"Can you come up with a plan for tonight? It's friday and I'm bored.\\" \n MoveAI: \\"Will any friends be coming along with you?\\" \n User: \\"No\\" \n MoveAI: {"message": \\"There is going to be an Ed Sheeran concert tonight in the Greek Theater in Berkeley at 10PM! You mentioned you love Ed Sheeran so I think you'll enjoy this.\\", "location": \\"Greek Theater in Berkeley\\", "description": \\"Ed Sheeran concert\\", "time": \\"10PM\\"}`
const isolateLocationPrompt = `Given a text, your task is to output a valid JSON string with two fields, location, and request. Only output this JSON when the given text directly specifies a location for the request. If there is no location, please ask for one first. \n\n User: What are some fun things my friends and I can do tonight? \n MoveAI: What location are you thinking of? \n User: New York \n MoveAI: {"request": \\"What are some fun things my friends and I can do tonight\\", "location":\\"New York\\"}`

const generateReplyPrompt = (activities, context, chatHistory, userName, request) => `${chatbotPersonaPrompt} \n Here are a set of activities: ${activities}, and relevant previous messages and preferences sent by ${userName}. Make sure to reference these if any are relevant to creating a personalized itinerary. \n ${outputPrompt} \n Example: \n ${exampleReplyPrompt} \n Chat History: \n ${chatHistory + userName}: ${request} \n MoveAI: `
const generateIsolateLocationPrompt = ( userMessage, chatHistory, userName ) => `${chatbotPersonaPrompt + isolateLocationPrompt + chatHistory} \n ${userName}: ${userMessage} \n MoveAI: `

module.exports = {generateMoveTitlePrompt, chatbotPersonaPrompt, generateReplyPrompt, generateIsolateLocationPrompt};